#!/bin/sh
# Regenerate tool-specific adapters from the canonical AGENTS.md.
#
# AGENTS.md is the single source of truth. Some tools read it natively and need
# nothing; the rest get a thin pointer generated here. Never edit the generated
# files — edit AGENTS.md and re-run this script.
#
# Usage: sh .agents/scripts/sync-agents.sh

set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
cd "$root"

if [ ! -f AGENTS.md ]; then
  echo "AGENTS.md not found in $root" >&2
  exit 1
fi

pointer='This project keeps its agent instructions in one place: **[AGENTS.md](AGENTS.md)**.

Read that file before making changes. It covers the hard rules (privacy, the
companion boundary, program integrity), the architecture, and the git workflow.'

# --- Claude Code -----------------------------------------------------------
cat > CLAUDE.md <<EOF
<!-- Generated by .agents/scripts/sync-agents.sh. Edit AGENTS.md instead. -->

@AGENTS.md

$pointer
EOF

# --- Cursor ----------------------------------------------------------------
mkdir -p .cursor/rules
cat > .cursor/rules/project.mdc <<EOF
---
description: Project rules, architecture, and git workflow
alwaysApply: true
---

<!-- Generated by .agents/scripts/sync-agents.sh. Edit AGENTS.md instead. -->

$pointer
EOF

# --- GitHub Copilot --------------------------------------------------------
mkdir -p .github
cat > .github/copilot-instructions.md <<EOF
<!-- Generated by .agents/scripts/sync-agents.sh. Edit AGENTS.md instead. -->

$pointer
EOF

# --- Claude Code dev-server config (untracked; derived from package.json) ---
# The canonical dev command is `npm run dev`, and the port is set in
# vite.config.ts. This file only teaches Claude Code's preview pane to use them.
mkdir -p .claude
cat > .claude/launch.json <<'EOF'
{
  "version": "0.0.1",
  "configurations": [
    {
      "name": "tracker",
      "runtimeExecutable": "npm",
      "runtimeArgs": ["run", "dev"],
      "port": 5173
    }
  ]
}
EOF

echo "Synced adapters from AGENTS.md:"
echo "  CLAUDE.md"
echo "  .cursor/rules/project.mdc"
echo "  .github/copilot-instructions.md"
echo "  .claude/launch.json (untracked)"
